"""schema initial

Migration structurante unique (§4 lot 0 et §6 du plan) : crée d'un coup les 28 tables des
3 jalons. Au-delà de ce qu'`autogenerate` produit depuis les modèles SQLAlchemy (tables,
contraintes, index, colonne générée `shooting.period` + son index GiST), cette révision
ajoute à la main ce qu'`autogenerate` ne sait pas produire :

- la séquence `invoice_number_seq`, consommée uniquement à l'émission d'une facture (§3-O) ;
- le trigger PL/pgSQL `invoice_line_immutable_trg` : interdit tout INSERT/UPDATE/DELETE sur
  `invoice_line` dès lors que la facture parente est `issued` ;
- le trigger PL/pgSQL `invoice_immutable_fields_trg` : interdit, sur une facture `issued`,
  la modification de `subtotal_cents`, `total_cents`, `vat_rate`, ainsi que le retour de
  `issued` vers `draft`.

Environnement jetable (AGENTS.md) : une seule révision par jalon, pas de dette de migration
à préserver.

Revision ID: 0001_schema_initial
Revises:
Create Date: 2026-08-20 15:15:33.363703
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_schema_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'photographer')", name=op.f("ck_app_user_role_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
    )
    op.create_table(
        "circuit",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="Europe/Paris", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_circuit")),
        sa.UniqueConstraint("name", name=op.f("uq_circuit_name")),
    )
    op.create_table(
        "client",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('team', 'driver', 'sponsor')", name=op.f("ck_client_kind_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client")),
        sa.UniqueConstraint("name", name=op.f("uq_client_name")),
    )
    op.create_table(
        "driver",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driver")),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("dedupe_key", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default="100", nullable=False),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'done', 'failed', 'dead')",
            name=op.f("ck_job_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index(
        "job_claim_idx",
        "job",
        ["priority", "run_at", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "job_dedupe_idx",
        "job",
        ["kind", "dedupe_key"],
        unique=True,
        # Correction revue J1 (🟠) : ne couvre plus `running` — voir `queue/enqueue.py`.
        postgresql_where=sa.text("dedupe_key IS NOT NULL AND status = 'pending'"),
    )
    op.create_index("job_recent_idx", "job", [sa.literal_column("created_at DESC")], unique=False)
    op.create_index(
        "job_stale_idx",
        "job",
        ["heartbeat_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "app_setting",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["app_user.id"],
            name=op.f("fk_app_setting_updated_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_setting")),
    )
    op.create_table(
        "camera",
        sa.Column("exif_serial", sa.String(length=255), nullable=True),
        sa.Column("make", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("owner_user_id", sa.BigInteger(), nullable=True),
        sa.Column("clock_offset_seconds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Europe/Paris", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["app_user.id"],
            name=op.f("fk_camera_owner_user_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_camera")),
        sa.UniqueConstraint("exif_serial", name=op.f("uq_camera_exif_serial")),
    )
    op.create_table(
        "job_execution_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("worker_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_job_execution_log_job_id_job"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_execution_log")),
        sa.UniqueConstraint("job_id", name=op.f("uq_job_execution_log_job_id")),
    )
    op.create_table(
        "shooting",
        sa.Column("client_id", sa.BigInteger(), nullable=True),
        sa.Column("circuit_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "period",
            postgresql.TSTZRANGE(),
            sa.Computed("tstzrange(starts_at, ends_at, '[)')", persisted=True),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=20), server_default="planned", nullable=False),
        sa.Column("quota_bytes", sa.BigInteger(), server_default="2147483648", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('planned', 'done')", name=op.f("ck_shooting_status_valid")),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_shooting_ends_after_starts")),
        sa.ForeignKeyConstraint(
            ["circuit_id"],
            ["circuit.id"],
            name=op.f("fk_shooting_circuit_id_circuit"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name=op.f("fk_shooting_client_id_client"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shooting")),
    )
    op.create_index(
        "ix_shooting_period_gist", "shooting", ["period"], unique=False, postgresql_using="gist"
    )
    op.create_index(
        "ix_shooting_starts_at", "shooting", [sa.literal_column("starts_at DESC")], unique=False
    )
    op.create_table(
        "team",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client.id"], name=op.f("fk_team_client_id_client"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
    )
    op.create_table(
        "collection",
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("shooting_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'closed')", name=op.f("ck_collection_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name=op.f("fk_collection_client_id_client"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_collection_created_by_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shooting_id"],
            ["shooting.id"],
            name=op.f("fk_collection_shooting_id_shooting"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection")),
    )
    op.create_index(
        "ix_collection_client_id_status", "collection", ["client_id", "status"], unique=False
    )
    op.create_table(
        "engagement",
        sa.Column("shooting_id", sa.BigInteger(), nullable=False),
        sa.Column("car_number", sa.String(length=10), nullable=False),
        sa.Column("driver_id", sa.BigInteger(), nullable=True),
        sa.Column("team_id", sa.BigInteger(), nullable=True),
        sa.Column("client_id", sa.BigInteger(), nullable=True),
        sa.Column("car_model", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name=op.f("fk_engagement_client_id_client"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["driver.id"],
            name=op.f("fk_engagement_driver_id_driver"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shooting_id"],
            ["shooting.id"],
            name=op.f("fk_engagement_shooting_id_shooting"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name=op.f("fk_engagement_team_id_team"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engagement")),
        sa.UniqueConstraint("shooting_id", "car_number", name="shooting_car_number"),
    )
    op.create_index("ix_engagement_client_id", "engagement", ["client_id"], unique=False)
    op.create_table(
        "quote",
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("circuit_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_shooting_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'sent', 'accepted', 'refused')", name=op.f("ck_quote_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["circuit_id"],
            ["circuit.id"],
            name=op.f("fk_quote_circuit_id_circuit"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name=op.f("fk_quote_client_id_client"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_shooting_id"],
            ["shooting.id"],
            name=op.f("fk_quote_created_shooting_id_shooting"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote")),
    )
    op.create_table(
        "shooting_staff",
        sa.Column("shooting_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["shooting_id"],
            ["shooting.id"],
            name=op.f("fk_shooting_staff_shooting_id_shooting"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_shooting_staff_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("shooting_id", "user_id", name=op.f("pk_shooting_staff")),
    )
    op.create_table(
        "upload_batch",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("shooting_hint_id", sa.BigInteger(), nullable=True),
        sa.Column("expected_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("received_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'processing', 'closed')", name=op.f("ck_upload_batch_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_upload_batch_created_by_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shooting_hint_id"],
            ["shooting.id"],
            name=op.f("fk_upload_batch_shooting_hint_id_shooting"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_batch")),
    )
    op.create_index(
        "ix_upload_batch_created_by_started_at",
        "upload_batch",
        ["created_by", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "client_selection",
        sa.Column("collection_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'validated')", name=op.f("ck_client_selection_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_client_selection_collection_id_collection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_selection")),
        sa.UniqueConstraint("collection_id", name=op.f("uq_client_selection_collection_id")),
    )
    op.create_table(
        "media",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.BigInteger(), nullable=False),
        sa.Column("uploaded_by", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("mime", sa.String(length=100), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("storage_key_hd", sa.Text(), nullable=True),
        sa.Column("storage_key_preview", sa.Text(), nullable=True),
        sa.Column("storage_key_thumb", sa.Text(), nullable=True),
        sa.Column("shot_at_exif", sa.DateTime(), nullable=True),
        sa.Column("shot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("camera_id", sa.BigInteger(), nullable=True),
        sa.Column("lens_model", sa.String(length=255), nullable=True),
        sa.Column("iso", sa.Integer(), nullable=True),
        sa.Column("shutter_speed_sec", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("shutter_speed_label", sa.String(length=50), nullable=True),
        sa.Column("aperture", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("focal_length", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("gps_lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("gps_lon", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("exif_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("phash", sa.BigInteger(), nullable=True),
        sa.Column("sharpness", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("series_id", sa.BigInteger(), nullable=True),
        sa.Column("is_series_representative", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("duplicate_of_media_id", sa.BigInteger(), nullable=True),
        sa.Column("ingest_status", sa.String(length=20), server_default="uploaded", nullable=False),
        sa.Column("quarantine_reason", sa.String(length=50), nullable=True),
        sa.Column("quarantine_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "attachment_status", sa.String(length=30), server_default="unattached", nullable=False
        ),
        sa.Column("attachment_source", sa.String(length=20), nullable=True),
        sa.Column("attachment_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("shooting_id", sa.BigInteger(), nullable=True),
        sa.Column("is_simulated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("keywords", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attachment_source IS NULL OR attachment_source IN ('pipeline_time', 'pipeline_ocr', 'human')",
            name=op.f("ck_media_attachment_source_valid"),
        ),
        sa.CheckConstraint(
            "attachment_status <> 'shooting_attached' OR shooting_id IS NOT NULL",
            name=op.f("ck_media_shooting_attached_requires_shooting"),
        ),
        sa.CheckConstraint(
            "attachment_status IN ('unattached', 'shooting_attached', 'engagement_attached', 'pending_review', 'inconsistent')",
            name=op.f("ck_media_attachment_status_valid"),
        ),
        sa.CheckConstraint(
            "ingest_status <> 'quarantined' OR quarantine_reason IS NOT NULL",
            name=op.f("ck_media_quarantine_reason_required"),
        ),
        sa.CheckConstraint(
            "ingest_status IN ('uploaded', 'processing', 'ingested', 'quarantined')",
            name=op.f("ck_media_ingest_status_valid"),
        ),
        sa.CheckConstraint(
            "quarantine_reason IS NULL OR quarantine_reason IN ('truncated_file', 'not_an_image', 'unsupported_mime', 'dimensions_out_of_range', 'aspect_ratio_out_of_range', 'exif_inconsistent', 'too_large', 'quota_exceeded', 'ingest_failed', 'orphan_object')",
            name=op.f("ck_media_quarantine_reason_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["upload_batch.id"],
            name=op.f("fk_media_batch_id_upload_batch"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["camera.id"],
            name=op.f("fk_media_camera_id_camera"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_media_id"],
            ["media.id"],
            name=op.f("fk_media_duplicate_of_media_id_media"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["media_series.id"],
            name=op.f("fk_media_series_id_media_series"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["shooting_id"],
            ["shooting.id"],
            name=op.f("fk_media_shooting_id_shooting"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["app_user.id"],
            name=op.f("fk_media_uploaded_by_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
        sa.UniqueConstraint("batch_id", "idempotency_key", name="batch_idempotency"),
    )
    op.create_index("ix_media_batch_id", "media", ["batch_id"], unique=False)
    op.create_index("ix_media_camera_id_shot_at", "media", ["camera_id", "shot_at"], unique=False)
    op.create_index("ix_media_content_hash", "media", ["content_hash"], unique=False)
    op.create_index(
        "ix_media_ingest_status_pending",
        "media",
        ["ingest_status"],
        unique=False,
        postgresql_where=sa.text("ingest_status <> 'ingested'"),
    )
    op.create_index(
        "ix_media_shooting_id_shot_at", "media", ["shooting_id", "shot_at"], unique=False
    )
    op.create_table(
        "share_link",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("collection_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("view_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_share_link_collection_id_collection"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_share_link_created_by_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_link")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_share_link_token_hash")),
    )
    op.create_table(
        "collection_item",
        sa.Column("collection_id", sa.BigInteger(), nullable=False),
        sa.Column("media_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_collection_item_collection_id_collection"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_collection_item_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("collection_id", "media_id", name=op.f("pk_collection_item")),
    )
    op.create_table(
        "delivery",
        sa.Column("collection_id", sa.BigInteger(), nullable=False),
        sa.Column("selection_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("item_count", sa.Integer(), nullable=True),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'building', 'ready', 'failed')",
            name=op.f("ck_delivery_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_delivery_collection_id_collection"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["client_selection.id"],
            name=op.f("fk_delivery_selection_id_client_selection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery")),
    )
    op.create_index("ix_delivery_selection_id", "delivery", ["selection_id"], unique=False)
    op.create_table(
        "invoice",
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("collection_id", sa.BigInteger(), nullable=False),
        sa.Column("selection_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subtotal_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "vat_rate", sa.Numeric(precision=5, scale=4), server_default="0.20", nullable=False
        ),
        sa.Column("total_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'issued' OR (number IS NOT NULL AND issued_at IS NOT NULL)",
            name=op.f("ck_invoice_issued_requires_number_and_date"),
        ),
        sa.CheckConstraint("status IN ('draft', 'issued')", name=op.f("ck_invoice_status_valid")),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name=op.f("fk_invoice_client_id_client"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_invoice_collection_id_collection"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["client_selection.id"],
            name=op.f("fk_invoice_selection_id_client_selection"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice")),
        sa.UniqueConstraint("number", name=op.f("uq_invoice_number")),
    )
    op.create_table(
        "media_engagement",
        sa.Column("media_id", sa.BigInteger(), nullable=False),
        sa.Column("engagement_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('ocr', 'human')", name=op.f("ck_media_engagement_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_media_engagement_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.id"],
            name=op.f("fk_media_engagement_engagement_id_engagement"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_media_engagement_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("media_id", "engagement_id", name=op.f("pk_media_engagement")),
    )
    op.create_index(
        "ix_media_engagement_engagement_id", "media_engagement", ["engagement_id"], unique=False
    )
    op.create_table(
        "media_ocr_candidate",
        sa.Column("media_id", sa.BigInteger(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("normalized_number", sa.String(length=10), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_version", sa.String(length=50), nullable=False),
        sa.Column("resolution", sa.String(length=20), nullable=False),
        sa.Column("engagement_id", sa.BigInteger(), nullable=True),
        sa.Column("resolved_by", sa.BigInteger(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "resolution IN ('auto', 'review', 'abstain', 'not_engaged', 'accepted', 'rejected')",
            name=op.f("ck_media_ocr_candidate_resolution_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["engagement_id"],
            ["engagement.id"],
            name=op.f("fk_media_ocr_candidate_engagement_id_engagement"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_media_ocr_candidate_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["app_user.id"],
            name=op.f("fk_media_ocr_candidate_resolved_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_ocr_candidate")),
    )
    op.create_index(
        "ix_media_ocr_candidate_media_id", "media_ocr_candidate", ["media_id"], unique=False
    )
    op.create_index(
        "ix_media_ocr_candidate_review",
        "media_ocr_candidate",
        ["resolution"],
        unique=False,
        postgresql_where=sa.text("resolution = 'review'"),
    )
    op.create_table(
        "media_search",
        sa.Column("media_id", sa.BigInteger(), nullable=False),
        sa.Column("shooting_id", sa.BigInteger(), nullable=True),
        sa.Column("uploaded_by", sa.BigInteger(), nullable=True),
        sa.Column("client_id", sa.BigInteger(), nullable=True),
        sa.Column("circuit_id", sa.BigInteger(), nullable=True),
        sa.Column("camera_id", sa.BigInteger(), nullable=True),
        sa.Column("lens_model", sa.String(length=255), nullable=True),
        sa.Column("attachment_status", sa.String(length=30), nullable=False),
        sa.Column("ingest_status", sa.String(length=20), server_default="uploaded", nullable=False),
        sa.Column("is_simulated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("series_id", sa.BigInteger(), nullable=True),
        sa.Column("shot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("iso", sa.Integer(), nullable=True),
        sa.Column("focal_length", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("team_ids", sa.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("driver_ids", sa.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("car_numbers", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("is_series_representative", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("duplicate_of_media_id", sa.BigInteger(), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_media_search_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("media_id", name=op.f("pk_media_search")),
    )
    op.create_index("ms_camera_idx", "media_search", ["camera_id"], unique=False)
    op.create_index("ms_client_idx", "media_search", ["client_id"], unique=False)
    op.create_index("ms_circuit_idx", "media_search", ["circuit_id"], unique=False)
    op.create_index("ms_uploaded_by_idx", "media_search", ["uploaded_by"], unique=False)
    op.create_index(
        "ms_drivers_gin", "media_search", ["driver_ids"], unique=False, postgresql_using="gin"
    )
    op.create_index("ms_focal_idx", "media_search", ["focal_length"], unique=False)
    op.create_index(
        "ms_fts_gin", "media_search", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_index("ms_iso_idx", "media_search", ["iso"], unique=False)
    op.create_index("ms_lens_idx", "media_search", ["lens_model"], unique=False)
    op.create_index(
        "ms_numbers_gin", "media_search", ["car_numbers"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ms_order_idx",
        "media_search",
        [sa.literal_column("shot_at DESC"), sa.literal_column("media_id DESC")],
        unique=False,
    )
    op.create_index(
        "ms_repr_idx",
        "media_search",
        [sa.literal_column("shot_at DESC")],
        unique=False,
        postgresql_where=sa.text("is_series_representative"),
    )
    op.create_index(
        "ms_shooting_idx",
        "media_search",
        ["shooting_id", sa.literal_column("shot_at DESC")],
        unique=False,
    )
    op.create_index("ms_status_idx", "media_search", ["attachment_status"], unique=False)
    op.create_index(
        "ms_teams_gin", "media_search", ["team_ids"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "media_series",
        sa.Column("shooting_id", sa.BigInteger(), nullable=False),
        sa.Column("camera_id", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("representative_media_id", sa.BigInteger(), nullable=True),
        sa.Column("member_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["camera.id"],
            name=op.f("fk_media_series_camera_id_camera"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["representative_media_id"],
            ["media.id"],
            name=op.f("fk_media_series_representative_media_id_media"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shooting_id"],
            ["shooting.id"],
            name=op.f("fk_media_series_shooting_id_shooting"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_series")),
    )
    op.create_index("ix_media_series_shooting_id", "media_series", ["shooting_id"], unique=False)
    op.create_table(
        "pipeline_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("media_id", sa.BigInteger(), nullable=True),
        sa.Column("batch_id", sa.BigInteger(), nullable=True),
        sa.Column("job_id", sa.BigInteger(), nullable=True),
        sa.Column("step", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["upload_batch.id"],
            name=op.f("fk_pipeline_event_batch_id_upload_batch"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_pipeline_event_job_id_job"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_pipeline_event_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_event")),
    )
    op.create_index(
        "ix_pipeline_event_batch_id_created_at",
        "pipeline_event",
        ["batch_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_pipeline_event_media_id_created_at",
        "pipeline_event",
        ["media_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "selection_item",
        sa.Column("selection_id", sa.BigInteger(), nullable=False),
        sa.Column("media_id", sa.BigInteger(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_selection_item_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["client_selection.id"],
            name=op.f("fk_selection_item_selection_id_client_selection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("selection_id", "media_id", name=op.f("pk_selection_item")),
    )
    op.create_table(
        "invoice_line",
        sa.Column("invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_price_cents", sa.BigInteger(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
            name=op.f("fk_invoice_line_invoice_id_invoice"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_line")),
    )
    # ### end Alembic commands ###

    # --- Décision O du plan : immuabilité de la facture émise, garantie en base ---

    # Numérotation : une séquence, consommée uniquement à l'émission (§3-O). Une facture
    # brouillon n'a pas de numéro.
    op.execute("CREATE SEQUENCE invoice_number_seq")

    # Trigger 1 : `invoice_line` est un snapshot immuable dès que la facture parente est
    # émise — aucun INSERT/UPDATE/DELETE n'y échappe, même hors du code applicatif.
    op.execute(
        """
        CREATE FUNCTION invoice_line_immutable() RETURNS trigger AS $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM invoice i
                 WHERE i.id = coalesce(NEW.invoice_id, OLD.invoice_id)
                   AND i.status = 'issued'
            ) THEN
                RAISE EXCEPTION 'facture émise : lignes immuables (invoice_id=%)',
                      coalesce(NEW.invoice_id, OLD.invoice_id);
            END IF;
            RETURN coalesce(NEW, OLD);
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER invoice_line_immutable_trg
            BEFORE INSERT OR UPDATE OR DELETE ON invoice_line
            FOR EACH ROW EXECUTE FUNCTION invoice_line_immutable()
        """
    )

    # Trigger 2 : une facture `issued` ne peut plus voir bouger ses champs financiers ni
    # repasser à `draft` — même via un `UPDATE` direct en base.
    op.execute(
        """
        CREATE FUNCTION invoice_immutable_fields() RETURNS trigger AS $$
        BEGIN
            IF OLD.status = 'issued' THEN
                IF NEW.subtotal_cents IS DISTINCT FROM OLD.subtotal_cents
                   OR NEW.total_cents IS DISTINCT FROM OLD.total_cents
                   OR NEW.vat_rate IS DISTINCT FROM OLD.vat_rate
                   OR NEW.status <> 'issued' THEN
                    RAISE EXCEPTION
                        'facture émise : champs financiers et statut immuables (invoice_id=%)',
                        OLD.id;
                END IF;
            END IF;
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER invoice_immutable_fields_trg
            BEFORE UPDATE ON invoice
            FOR EACH ROW EXECUTE FUNCTION invoice_immutable_fields()
        """
    )


def downgrade() -> None:
    # --- Décision O : défaire les triggers/fonctions/séquence avant de toucher aux tables ---
    op.execute("DROP TRIGGER IF EXISTS invoice_immutable_fields_trg ON invoice")
    op.execute("DROP FUNCTION IF EXISTS invoice_immutable_fields()")
    op.execute("DROP TRIGGER IF EXISTS invoice_line_immutable_trg ON invoice_line")
    op.execute("DROP FUNCTION IF EXISTS invoice_line_immutable()")
    op.execute("DROP SEQUENCE IF EXISTS invoice_number_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invoice_line")
    op.drop_table("selection_item")
    op.drop_index("ix_pipeline_event_media_id_created_at", table_name="pipeline_event")
    op.drop_index("ix_pipeline_event_batch_id_created_at", table_name="pipeline_event")
    op.drop_table("pipeline_event")
    op.drop_index("ix_media_series_shooting_id", table_name="media_series")
    op.drop_table("media_series")
    op.drop_index("ms_teams_gin", table_name="media_search", postgresql_using="gin")
    op.drop_index("ms_status_idx", table_name="media_search")
    op.drop_index("ms_shooting_idx", table_name="media_search")
    op.drop_index(
        "ms_repr_idx",
        table_name="media_search",
        postgresql_where=sa.text("is_series_representative"),
    )
    op.drop_index("ms_order_idx", table_name="media_search")
    op.drop_index("ms_numbers_gin", table_name="media_search", postgresql_using="gin")
    op.drop_index("ms_lens_idx", table_name="media_search")
    op.drop_index("ms_iso_idx", table_name="media_search")
    op.drop_index("ms_fts_gin", table_name="media_search", postgresql_using="gin")
    op.drop_index("ms_focal_idx", table_name="media_search")
    op.drop_index("ms_drivers_gin", table_name="media_search", postgresql_using="gin")
    op.drop_index("ms_client_idx", table_name="media_search")
    op.drop_index("ms_camera_idx", table_name="media_search")
    op.drop_table("media_search")
    op.drop_index(
        "ix_media_ocr_candidate_review",
        table_name="media_ocr_candidate",
        postgresql_where=sa.text("resolution = 'review'"),
    )
    op.drop_index("ix_media_ocr_candidate_media_id", table_name="media_ocr_candidate")
    op.drop_table("media_ocr_candidate")
    op.drop_index("ix_media_engagement_engagement_id", table_name="media_engagement")
    op.drop_table("media_engagement")
    op.drop_table("invoice")
    op.drop_index("ix_delivery_selection_id", table_name="delivery")
    op.drop_table("delivery")
    op.drop_table("collection_item")
    op.drop_table("share_link")
    op.drop_index("ix_media_shooting_id_shot_at", table_name="media")
    op.drop_index(
        "ix_media_ingest_status_pending",
        table_name="media",
        postgresql_where=sa.text("ingest_status <> 'ingested'"),
    )
    op.drop_index("ix_media_content_hash", table_name="media")
    op.drop_index("ix_media_camera_id_shot_at", table_name="media")
    op.drop_index("ix_media_batch_id", table_name="media")
    op.drop_table("media")
    op.drop_table("client_selection")
    op.drop_index("ix_upload_batch_created_by_started_at", table_name="upload_batch")
    op.drop_table("upload_batch")
    op.drop_table("shooting_staff")
    op.drop_table("quote")
    op.drop_index("ix_engagement_client_id", table_name="engagement")
    op.drop_table("engagement")
    op.drop_index("ix_collection_client_id_status", table_name="collection")
    op.drop_table("collection")
    op.drop_table("team")
    op.drop_index("ix_shooting_starts_at", table_name="shooting")
    op.drop_index("ix_shooting_period_gist", table_name="shooting", postgresql_using="gist")
    op.drop_table("shooting")
    op.drop_table("job_execution_log")
    op.drop_table("camera")
    op.drop_table("app_setting")
    op.drop_index("job_stale_idx", table_name="job", postgresql_where=sa.text("status = 'running'"))
    op.drop_index("job_recent_idx", table_name="job")
    op.drop_index(
        "job_dedupe_idx",
        table_name="job",
        postgresql_where=sa.text("dedupe_key IS NOT NULL AND status = 'pending'"),
    )
    op.drop_index("job_claim_idx", table_name="job", postgresql_where=sa.text("status = 'pending'"))
    op.drop_table("job")
    op.drop_table("driver")
    op.drop_table("client")
    op.drop_table("circuit")
    op.drop_table("app_user")
    # ### end Alembic commands ###
